var githubuser= {login: "Cohen611",
id: 17028961,
avatar_url: "https://avatars.githubusercontent.com/u/17028961?v=3",
gravatar_id: "",
url: "https://api.github.com/users/Cohen611",
html_url: "https://github.com/Cohen611",
followers_url: "https://api.github.com/users/Cohen611/followers",
following_url: "https://api.github.com/users/Cohen611/following{/other_user}",
gists_url: "https://api.github.com/users/Cohen611/gists{/gist_id}",
starred_url: "https://api.github.com/users/Cohen611/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/Cohen611/subscriptions",
organizations_url: "https://api.github.com/users/Cohen611/orgs",
repos_url: "https://api.github.com/users/Cohen611/repos",
events_url: "https://api.github.com/users/Cohen611/events{/privacy}",
received_events_url: "https://api.github.com/users/Cohen611/received_events",
type: "User",
site_admin: false,
name: "Candace Cohen",
company: null,
blog: null,
location: null,
email: null,
hireable: null,
bio: null,
public_repos: 8,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2016-02-02T15:58:17Z",
updated_at: "2016-02-04T06:37:22Z"
};
